name: bubble_lens_example
description: Demonstrates how to use the bubble_lens package.

version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bubble_lens:
    path: ../

flutter:
  uses-material-design: true
